### PR TITLE
Modulus APP_DIR is not correct use productionPrivateDir() instead

### PR DESCRIPTION
**Pull request by steve-ross**
On the new meteor containers at modulus the APP_DIR is incorrect or no longer needed. Need to use productionPrivateDir to get the path or you will get template not found errors in production.

### CODE REVIEW

**Comment by steve-ross** [comment]
I reported the issue with Modulus. We had an app break in production where we couldn't send any emails and this fixed the issue.

**Comment by johanbrook** [comment]
Gotcha, thank you. Is `APP_DIR` completely deprecated, so it's safe to move away from it here?

**Comment by steve-ross** [comment]
Not sure, I'll ask modulus support. All I know is that it is one directory up from where productionPrivateDir is at this point.

**Comment by johanbrook** [comment]
So would it make sense to fallback to `APP_DIR`, instead of removing it for now?

**Comment by steve-ross** [comment]
It may be that you just need to tack on 'bundle' if APP_DIR is defined.
APP_DIR = /mnt/app 
productionPrivateDir() = /mnt/app/bundle

**Comment by steve-ross** [comment]
Apparently that is a bug on modulus, they opened a ticket:

https://github.com/onmodulus/docker-build-meteor/issues/14

**Comment by ivanthemeh** [comment]
Where does this productionPrivateDir() = /mnt/app/bundle and APP_DIR = /mnt/app  get set at? In modulus env vars or in meteor_settings?
Please help out someone, my localhost is working for these but not modulus container

**Comment by johanbrook** [comment]
@ivanthemeh You mean in this package or on Modulus? This package set path things in https://github.com/lookback/meteor-emails/blob/master/lib/utils.js#L40.

**Comment by ivanthemeh** [comment]
So do I need to add that and fork it or is it already added? My emails were working fine on modulus server and then all of a sudden it quit finding the templates. Please help, thanks!

**Comment by johanbrook** [comment]
Try cloning this package locally into your Meteor app, do the necessary change above, and deploy to Modulus to see if it works. I haven't ever dealt with Modulus, so I can't sadly test it.

**Comment by steve-ross** [comment]
closing, we have been using this in production for months, opening another PR which will contain this fix and a fix for meteor 1.3+

**Pull request closed without merging**
