### PR TITLE
Working around meteor packaging issue, and adding underscore as NPM d…

### PR DESCRIPTION
**Pull request by grabcode**
…ependancy, not atmosphere one.

### CODE REVIEW

**Comment by johanbrook** [comment]
Cool, does this run for you okay in the embedded sample app? I'll give it a run tomorrow as well. It looks like the package builds okay for people when it's embedded in a Meteor app, but fails when building from Atmosphere.

**Comment by grabcode** [comment]
I haven't tried the embedded app, but did in my app, and it worked just fine.

**Comment by johanbrook** [comment]
Alright! I'll give it a run.

**Comment by grabcode** [comment]
I've fixed the lint issue 👍

**Comment by johanbrook** [comment]
Hm, this worked in the example app when I pulled this branch and built it. But after merging, it yielded the same errors as in the issue.

**Pull request merged**
