### PR TITLE
0.4.3

### PR DESCRIPTION
**Pull request by chrisbutler**

### CODE REVIEW

**Comment by chrisbutler** [comment]
@johanbrook i should have done this all in one shot... but if you could update the package on atmosphere it would be most appreciated

**Comment by johanbrook** [comment]
@chrisbutler I'm on this already, thanks anyway for the PR!

**Comment by johanbrook** [comment]
Published: https://atmospherejs.com/lookback/emails.

**Comment by chrisbutler** [comment]
:+1: thank you!

**Comment by johanbrook** [comment]
Thank _you_!

**Pull request closed without merging**
