### PR TITLE
add modulus support

### LINKED ISSUE #16: Modulus support?
I am unable to get this package running on modulus. While I can set environmental variables, the actual path is subject to change and I have yet to uncover a method for exposing the path.

### PR DESCRIPTION
**Pull request by adamwong246**
This PR is based on my communications with Modulus support http://help.modulus.io/customer/en_us/portal/questions/12745491--dirname?new=12745491

Fixes #16

### CODE REVIEW

**Comment by johanbrook** [comment]
Thanks a lot, @adamwong246 ! Great that you added a comment as well.

Do you mind adding some sentences to [this section](https://github.com/lookback/meteor-emails#important-note-regarding-template-paths) in the README as well?

**Comment by adamwong246** [comment]
@structuresound Can you revert that change? Since this PR is on the cusp of being approved, I don't think we need a custom email package anyways.

**Comment by johanbrook** [comment]
Agreed. Please revert to original name for this repo. 

@adamwong246 Great! The numbered list in the README section won't render as Markdown though – you need some whitespace around it. Just a head's up.

**Comment by adamwong246** [comment]
@johanbrook the name of the package ahas been reverted and a line added to the README for proper markdown

**Comment by johanbrook** [comment]
Thanks! Merging.

**Pull request merged**
